name: Post-Merge
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  component-tests:
    name: Component tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Run component tests
        run: |
          nix-shell --run "npm run test"
      - name: Archive component tests results
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles('reports/*') }}
        with:
          name: component-test-report
          path: reports
  api-tests:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install Playwright
        run: |
          nix-shell --run "npx playwright install chromium --with-deps"
      - name: Build pieces
        run: |
          nix-shell --run "npm run build"
      - name: Start neo4j
        run: |
          bin/neo4j-init --script src/lib/data/kennedies.cypher
      - name: Run API tests
        run: |
          nix-shell --run "npx playwright test"
      - name: Archive API tests results
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles('playwright/reports/*') }}
        with:
          name: api-test-report
          path: playwright/reports
