name: Merge
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Run component tests
        run: |
          nix-shell --run "npm run test"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Run component tests
        run: |
          nix-shell --run "npm run test"
  api-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Start neo4j
        run: |
          netstat -plunt
          bin/neo4j-init --script src/lib/data/kennedies.cypher
      - name: Build
        run: |
          nix-shell --run "npm run build"
      - name: Start the app
        run: |
          nix-shell --run "npm start" &
      - name: Run API tests
        run: |
          npx playwright test
        env:
          HOME: /root
