name: Merge
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm clean-install
      - name: Run component tests
        run: npm run test
  api-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        run: npm run build
      - name: Start neo4j
        run: bin/neo4j-init --script src/lib/data/kennedies.cypher
      - name: Start app
        run: |
          npm start &
          sleep 10
      - name: Run API tests
        run: npx playwright test
        env:
          HOME: /root

