name: CI

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      # Install all used/required dependencies
      - name: Prepare environment
        run: |
          nix-shell bin/shell.nix --run "echo neo4j installed."
          nix-shell --run "npx playwright install chromium --with-deps; echo Development tools installed."

      # Build the app
      - name: Build
        id: build
        continue-on-error: true
        run: |
          nix-shell --run "npm run build"

      # Run component tests even if build failed
      - name: Test components
        if: always()
        continue-on-error: true
        run: |
          nix-shell --run "npm run test"

      # Start neo4j server and populate it with test data
      - name: Start neo4j
        id: neo4j
        if: always() && steps.build.outcome == 'success'
        run: |
          bin/neo4j-init --script src/lib/data/kennedies.cypher

      # Run API tests
      - name: Test API
        if: always() && steps.build.outcome == 'success' && steps.neo4j.outcome == 'success'
        continue-on-error: true
        run: |
          nix-shell --run "npx playwright test"

      # Run end to end tests
      - name: Test UI
        if: always() && steps.build.outcome == 'success' && steps.neo4j.outcome == 'success'
        continue-on-error: true
        run: |
          nix-shell --run "npm start & npx cypress run --browser firefox"

      # Run k6
      - name: Load test
        if: always() && steps.build.outcome == 'success' && steps.neo4j.outcome == 'success'
        continue-on-error: true
        run: |
          nix-shell --run "npm start >/dev/null & k6 run k6/calendar.js"

      # Archive results
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            reports
            playwright/reports
            cypress/test-results
          if-no-files-found: ignore
